### ISSUE TITLE
Allow executing withdrawals before expiry if the market is closed

### ISSUE THREAD

**Issue by d1ll0n** [wildcat-finance/v2-protocol#10]
## Description

Lenders currently have to wait until a withdrawal batch expires before they can execute their withdrawal, even if the market is closed. This is a byproduct of the way withdrawal execution is handled, and it's not ideal.

**Note** Do not update main branch or develop branch of front-end, or main branch of wildcat.ts until we have the new contracts deployed, otherwise it will break the current front-end.

Below are the files that will be affected by this and some considerations for how to fix the issue.

### wildcat-finance/wildcat.ts

In [src/withdrawal-batch.ts](https://github.com/wildcat-finance/wildcat.ts/blob/main/src/withdrawal-batch.ts)
- `get isExpired`
- `applyLensUpdate`
- `fromSubgraphWithdrawalBatch`

### wildcat-finance/wildcat-app-v2

[todo: identify]

### wildcat-finance/v2-protocol

In [src/market/WildcatMarketWithdrawals](https://github.com/wildcat-finance/v2-protocol/blob/main/src/market/WildcatMarketWithdrawals.sol#L54)
- `getAvailableWithdrawalAmount`
- `executeWithdrawal`
- `_executeWithdrawal`

## Tasks

Determine whether we should only remove the check on execution, or if we should also skip queuing requests altogether once the market is already closed. The latter may cause issues with our indexing off-chain on thegraph, but may be safer.

-  [x] Consider what happens when lenders are able to execute withdrawals from unexpired batches once the market is closed, given that other withdrawals can be queued afterwards.
    - I recall there being an issue with this related to batch durations of 0, so we should double check this won't be an issue.
    - If it *is* an issue, then we can just go with not creating new requests after the market is closed, and always immediately executing queued withdrawals without assigning a batch. This will likely require changing the subgraph a bit, but it shouldn't be too bad.

- [x] Either update the market contracts to execute withdrawals prior to expiry without changing the queue withdrawal system, or update `queueWithdrawal` to immediately execute without creating a batch once the market is closed.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [x] **Scenario: Executing withdrawals before expiry if market is closed**
  - Given the market is closed
  - When a lender attempts to execute their withdrawal before expiry
  - Then the withdrawal should be executed successfully without waiting for the batch expiration
