### ISSUE TITLE
Set min deposit amount for lenders

### ISSUE THREAD

**Issue by andfletcher** [wildcat-finance/v2-protocol#11]
## Description

Allow setting minimum deposit amount per market.

Should probably go into the hooks contract rather than the core market contract

## Todo

- [x] Create figma flow / add it to the create market and change market paramter screens.
- [ ] Make changes in contract
- [ ] Implement on frontend

## Acceptance Criteria

Borrower can set a minimum deposit amount for a market.

Q: Should they be able to change this?

## Additional Information
- min deposit < then max capacity (just a info that we need to make this check on the frontend side)
